# Generated by Django 5.2.10 on 2026-03-19 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('grupa', models.TextField(blank=True, null=True)),
                ('specialty_id', models.IntegerField(blank=True, null=True)),
                ('kurs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('kod', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('mesto', models.TextField(blank=True, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('boss_organization', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Practices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_id', models.IntegerField(blank=True, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('practice_type_id', models.IntegerField(blank=True, null=True)),
                ('module_id', models.IntegerField(blank=True, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('library', models.TextField(blank=True, null=True)),
                ('ruka', models.TextField(blank=True, null=True)),
                ('date_begin', models.TextField(blank=True, null=True)),
                ('date_finish', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('not_day_one', models.IntegerField(blank=True, null=True)),
                ('not_day_two', models.IntegerField(blank=True, null=True)),
                ('special', models.TextField(blank=True, null=True)),
                ('good', models.TextField(blank=True, null=True)),
                ('attestation_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'practices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PracticeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type_id', models.IntegerField(blank=True, null=True)),
                ('vid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'practice_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_id', models.IntegerField(blank=True, null=True)),
                ('spec', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specialties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('fio', models.TextField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('education_form_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=255)),
                ('spec', models.CharField(blank=True, max_length=255)),
                ('grupa', models.CharField(blank=True, max_length=100)),
                ('kurs', models.PositiveIntegerField(blank=True, null=True)),
                ('obuch', models.CharField(blank=True, max_length=100)),
                ('vid', models.CharField(blank=True, max_length=100)),
                ('kod', models.CharField(blank=True, max_length=100)),
                ('mesto', models.CharField(blank=True, max_length=255)),
                ('adress', models.CharField(blank=True, max_length=255)),
                ('library', models.CharField(blank=True, max_length=255)),
                ('ruka', models.CharField(blank=True, max_length=255)),
                ('boss_organization', models.CharField(blank=True, max_length=255)),
                ('date_begin', models.DateField(blank=True, null=True)),
                ('date_finish', models.DateField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('not_day_one', models.PositiveIntegerField(blank=True, null=True)),
                ('not_day_two', models.PositiveIntegerField(blank=True, null=True)),
                ('special', models.CharField(blank=True, max_length=255)),
                ('good', models.TextField(blank=True)),
                ('attestation_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
