# Generated by Django 6.0.4 on 2026-04-24 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainNNV', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200, verbose_name='Документ')),
                ('action', models.CharField(default='download', max_length=100, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История документа',
                'verbose_name_plural': 'История документов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.DeleteModel(
            name='Organizations',
        ),
        migrations.DeleteModel(
            name='Practices',
        ),
        migrations.DeleteModel(
            name='PracticeTypes',
        ),
        migrations.DeleteModel(
            name='Specialties',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='attestation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата аттестации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='boss_organization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Руководитель от организации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_begin',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fio',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='good',
            field=models.CharField(blank=True, max_length=200, verbose_name='Качество выполнения работы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grupa',
            field=models.CharField(blank=True, max_length=50, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kod',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код модуля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kurs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='library',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mesto',
            field=models.CharField(blank=True, max_length=300, verbose_name='Место прохождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='not_day_one',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Пропущено дней'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='not_day_two',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='По неуважительной причине'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Количество дней'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='obuch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ruka',
            field=models.CharField(blank=True, max_length=200, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spec',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='special',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специальность для характеристики'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vid',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вид практики'),
        ),
    ]
